server.port=${PORT:8080}

spring.application.name=conectasaude
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://nicholas_db:200604@cluster0.p737yt3.mongodb.net/conectasaude?appName=Cluster0}
spring.data.mongodb.auto-index-creation=true
spring.session.store-type=mongodb
spring.session.mongodb.collection-name=sessoes_login
spring.thymeleaf.cache=false

app.name=${APP_NAME:ConectaSaude}
app.theme.name=${APP_THEME:default}
app.admin.email=${APP_ADMIN_EMAIL:admin@conectasaude.com}
app.admin.password=${APP_ADMIN_PASSWORD:Admin@12345}
